### ISSUE TITLE
Add `unscheduled` icon

### ISSUE THREAD

**Issue by dyroffk-getjobber** [GetJobber/atlantis#1769]
The designs for the new Schedule view in Jobber online use an 'unscheduled' icon that's present in the design system [iconography figma](https://www.figma.com/file/HXWXusJPZLmaJNGlKEpiyhXW/Product%2FBase?type=design&node-id=13834-6&mode=design&t=BEsR0ztqwKBjdWr5-0), but not yet in Atlantis

<img width="521" alt="image" src="https://github.com/GetJobber/atlantis/assets/140410985/c89f996b-cd5a-4cb8-ad9b-57047c436237">

I've exported the SVG from figma, bootstrapped locally, and confirmed it looks as expected in storybook, ~but I don't seem to have permission to push up the branch to create a PR.~  Sorry, silly me cloned via http instead of ssh

<img width="393" alt="image" src="https://github.com/GetJobber/atlantis/assets/140410985/27ac6777-4c83-4c87-b9ab-98e825f4cf59">

**Comment by dyroffk-getjobber** [comment]
See: https://github.com/GetJobber/atlantis/pull/1770

**Comment by chris-at-jobber** [comment]
PR merged!
