### ISSUE TITLE
Implement keyboard shortcuts to close and confirm for ConfirmationModal

### ISSUE THREAD

**Issue by seanhealy** [GetJobber/atlantis#378]
The Confirmation Modal's keyboard shortcuts can be improved.
- https://atlantis.getjobber.com/components/confirmation-modal

Expected Behaviour
- on `escape`, should close the confirmation modal and trigger `onCancel` and `onRequestClose`
- `enter`, if not focused on any elements, should trigger `onConfirm` and `onRequestClose`

**Comment by 0length** [comment]
@seanhealy I'd like to work on this issue.

**Comment by chris-at-jobber** [comment]
@0length thanks! [Modal](https://atlantis.getjobber.com/components/modal) has this behaviour already, so there's a point of reference for you to start with 😃

**Comment by 0length** [comment]
@chris-at-jobber Oke thanks for the clue. i will use same behaviour as like as modal.
