### ISSUE TITLE
Autocomplete should not show empty section headers

### ISSUE THREAD

**Issue by seanhealy** [GetJobber/atlantis#379]
Related Components:
- https://atlantis.getjobber.com/components/autocomplete#section-headings

If there are no options in a section hide the section header.

Example:

![image](https://user-images.githubusercontent.com/131327/96309239-27c18c80-0fc2-11eb-9719-33fb95f4930a.png)

**Comment by merelj** [comment]
I'd like to work on this one if you don't mind
