### ISSUE TITLE
Add ability to use markdown for ConfirmationModal

### ISSUE THREAD

**Issue by seanhealy** [GetJobber/atlantis#381]
Related Components:
- https://atlantis.getjobber.com/components/confirmation-modal
- https://atlantis.getjobber.com/components/markdown

The `message` prop should accept markdown.

This can be done using the [`Markdown` component](https://atlantis.getjobber.com/components/markdown).

**Comment by joelwarrington-jobber** [comment]
Ability to accept markdown was implemented by https://github.com/GetJobber/atlantis/pull/424
