### ISSUE TITLE
Update Tooltip to use React Popper

### ISSUE THREAD

**Issue by seanhealy** [GetJobber/atlantis#383]
Related Components:
- https://atlantis.getjobber.com/components/tooltip

The Tooltip currently uses a [non-react version of popper.js](https://popper.js.org/docs/v2/) and is a bit messy as a result. We should update it to use [React Popper](https://popper.js.org/react-popper/). This will also resolve some positioning edge cases.

**Comment by felix-chin** [comment]
@seanhealy I'd like to work on this issue.

**Comment by chris-at-jobber** [comment]
@felix-chin Thanks!

**Comment by ArpitaGanatra** [comment]
is the issue still open? I had like to work on this

**Comment by chris-at-jobber** [comment]
@ArpitaGanatra please feel free to put up a PR for this 👍

**Comment by joelwarrington-jobber** [comment]
Tooltip has been updated to use Popper as of #201
