### ISSUE TITLE
Adjust padding on buttons with icons relative to size

### ISSUE THREAD

**Issue by seanhealy** [GetJobber/atlantis#384]
Related Components:
- https://atlantis.getjobber.com/components/button

Currently our buttons have different padding based on what size prop is being used. (Small 8px, Base 12px, Large 16px).

However, one an icon prop is introduced, the padding defaults to 16px regardless of size. The padding should stay the same according to its size.

Small button with 8px padding
![image](https://user-images.githubusercontent.com/131327/96310145-fc3fa180-0fc3-11eb-8e7a-f7553856fde2.png)

Padding changes to 16px when icon is introduced
![image](https://user-images.githubusercontent.com/131327/96310161-0366af80-0fc4-11eb-9930-6f2dbe9b16c1.png)

Base button with 12px padding
![image](https://user-images.githubusercontent.com/131327/96310173-095c9080-0fc4-11eb-8664-20f8d3d44dd1.png)

Padding changes to 16px when an icon is introduced
**INCLUDE IMAGE**
![image](https://user-images.githubusercontent.com/131327/96310182-0eb9db00-0fc4-11eb-8574-4d3dba15412a.png)

**Comment by 0length** [comment]
@seanhealy I'd like to work on this issue.

**Comment by chris-at-jobber** [comment]
Issue resolved, thanks @0length !
