### ISSUE TITLE
Modal should receive focus when opened

### ISSUE THREAD

**Issue by seanhealy** [GetJobber/atlantis#385]
Related Components:
- https://atlantis.getjobber.com/components/modal

When a modal is opened, you still have to tab through all the content of the page to get to it. Tab and Shift + Tab should not focus outside of the modal. When a dialog opens, focus moves to an element inside the dialog. 

https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=111%2C122%2C131%2C132%2C133%2C141%2C143%2C144%2C146%2C148%2C1410%2C1411%2C1412%2C1413%2C211%2C212%2C223%2C224%2C225%2C226%2C241%2C242%2C243#focus-order

**Comment by voodoods** [comment]
I'd like to work on that.

**Comment by chris-at-jobber** [comment]
Issue resolved, thanks @voodoods !
