### ISSUE TITLE
<Tabs> Component to allow props for default opened tab

### ISSUE THREAD

**Issue by kingstonfung** [GetJobber/atlantis#521]
**Component in question:**
https://atlantis.getjobber.com/components/tabs

**Proposing enhancement(s):**
Allowing a props (eg: `selectedTab`) to be used for selected the default opened Tab

```jsx
<Tabs selectedTab={1}>
  <Tab label="Eggs"></Tab>
  <Tab label="Cheese"></Tab> {*/ This will be the opened tab by default */}
</Tabs>
```

**Use Case and Reasoning:**
If we want to restore the state for the `<Tabs>` component, right now we couldn't preselect a `<Tab>` and bring the user back to the correct context.

More specifically, let's say we use `<Tabs>` inside of a `<Modal>` component and if the user comes back to either continue their workflow, or edit some information, we would like to bring them back to the exact view with pre-populated information, allowing them to resume their workflows.

**Comment by chris-at-jobber** [comment]
Have discussed this and deemed it unnecessary - the proposed design that required a default Tab was actually a misuse of Tab.
