### ISSUE TITLE
Create a CHANGELOG.md file

### ISSUE THREAD

**Issue by andrewjdmccann** [GetJobber/atlantis#6]
Guide
https://keepachangelog.com/en/1.0.0/

**Comment by seanhealy** [comment]
I think we can automate this for releases with something like:
https://github.com/semantic-release/semantic-release

**Comment by seanhealy** [comment]
We could look at this for enforcing PR naming

https://github.com/probot/semantic-pull-requests

**Comment by seanhealy** [comment]
Resolved
