### ISSUE TITLE
Add actions to Card component

### ISSUE THREAD

**Issue by joelzwarrington** [GetJobber/atlantis#656]
The [Card component](https://atlantis.getjobber.com/components/card) is aesthetically similar to the [Modal component](https://atlantis.getjobber.com/components/modal), however it does not have the ability to provide actions.

- Add ability to specify actions
  - primary action
  - secondary action
  - tertiary action

![image](https://user-images.githubusercontent.com/80279872/133650941-51944951-5790-4d03-9f0b-289ed8ed4878.png)

**Comment by joelwarrington-jobber** [comment]
@chris-at-jobber thoughts on adding actions to the card component?

**Comment by chris-at-jobber** [comment]
I'm not sure the use case is similar enough, but we do have some design work in the backlog to revisit "actions bars" like the one in Modal, so I'd wait until that's resolved before taking another look at this.

**Comment by joelzwarrington** [comment]
@chris-at-jobber wondering if you had a chance to revisit action bars yet? Do you want me to propose something more concrete or are there still things in the works?

**Comment by chris-at-jobber** [comment]
Closing this issue as we've added actions to the [card header](https://atlantis.getjobber.com/?path=/docs/components-card--card)
