### ISSUE TITLE
Implement component to display placeholder for content (skeleton/placeholder)

### ISSUE THREAD

**Issue by joelzwarrington** [GetJobber/atlantis#660]
It would be nice to have a component to be used to display placeholder content when API/HTTP or asynchronous actions are taking place.

Examples:
- https://ant.design/components/skeleton/
- https://react.semantic-ui.com/elements/placeholder/
- https://mui.com/components/skeleton
- https://polaris.shopify.com/components/feedback-indicators/skeleton-page

Related to #649

**Comment by chris-at-jobber** [comment]
One question from my side is... could we make this something that components handle on their own? Is that the intention? The thing I like about the approach in [#649](https://github.com/GetJobber/atlantis/pull/649l) (and our current approach in the web app) is the simplicity of setting a loading state once, with all of the content in that region being taken care of by what's effectively an umbrella state.

```
 <Section that's loading>
  <All of the children clearly placed into a loading state>
</Section that's loading>
```

I love the visual approach of the skeleton/placeholder, I'm wondering if there's something we can do from the systems side to make it something that effectively self-implements based on the components, or if this would mean teams need to manually layout loading states? 

(This might have an obvious or easy answer technically, my only experience with this was playing around with a Vue app a few years ago that had a somewhat manual per-layout implementation)

**Comment by eddysims** [comment]
@joelwarrington-jobber @chris-at-jobber going to remove the labels off of this, as I think that this needs some design thought before we begin working on it.

**Comment by joelwarrington-jobber** [comment]
@chris-at-jobber I think that might be a good approach.

- Each component implements it's own skeleton state
- Implement component such as section which accepts a loading boolean prop
- Initialize skeleton context in the section component, and wrap it's children in a provider
- Each component that has a skeleton state, could see if they're being wrapped by that section component and if loading is true

@eddysims / @darryltec wondering what your thoughts are on that?

Another approach could be to create a generic skeleton component, which will let people model their own content like:
```
<Card>
  <Skeleton type="circle" ...other props which affect the display of the skeleton />
  <Skeleton type="heading" />
  <Skeleton type="paragraph" />
</Card>
```

**Comment by chris-at-jobber** [comment]
@joelzwarrington we've added the [Glimmer](https://atlantis.getjobber.com/?path=/docs/components-status-and-feedback-glimmer-docs--page) component which we believe could be extended in the future to handle templated "page skeletons". I think it covers the sentiment of what you're looking for with this issue?

**Comment by joelzwarrington** [comment]
hey @chris-at-jobber  - that's awesome, looks great!
