### ISSUE TITLE
Playground examples take up too much vertical space

### ISSUE THREAD

**Issue by chris-at-jobber** [GetJobber/atlantis#675]
As a consumer of Atlantis docs, I want to be able to focus on the right content in examples so that I can absorb the right information.

## Pain point 
Currently our [Playground](https://github.com/GetJobber/atlantis/blob/master/packages/docz-tools/src/gatsby-theme-docz/components/Playground/Playground.tsx) takes up a ton of vertical space with the code sandbox. This is fine when the intent is to highlight technical patterns, but for design usage examples we end up with more visual space allocated to code examples than the guidelines and visual examples themselves. It makes documentation for relatively simple components like Avatar and Emphasis seem overwhelming.

## Potential solution
Add a prop to Playground that defaults to closed/minimized, with an option for the user to expand. Allow for code-specific Playgrounds to be set to "open" by default if needed.

## Examples
![image](https://user-images.githubusercontent.com/39704901/134418369-8f6a43f7-83fe-42f0-a969-dcf4db6108ec.png)
![image](https://user-images.githubusercontent.com/39704901/134418323-64040a69-d273-4322-ac01-43c625c46ceb.png)
![image](https://user-images.githubusercontent.com/39704901/134418137-d78ef643-b15a-49de-a71a-5cf69099fb85.png)
![image](https://user-images.githubusercontent.com/39704901/134418165-2bd0afcf-e4f8-4291-a167-e46d677748d9.png)

**Comment by joelwarrington-jobber** [comment]
Having the option to have the playground act like a [Disclosure](https://atlantis.getjobber.com/components/disclosure) would be great! So that you can focus on the component variations and if you want to see code examples can view it.

I also really like how [Semantic UI React](https://react.semantic-ui.com/elements/button/#types-emphasis) also adds links to open the component in a full-page, and also go to a codesandbox.

**Comment by Bhavin789** [comment]
Hi @joelwarrington-jobber @chris-at-jobber, I was looking at this issue. Got to know that Docz actually removed the support for the same in recent versions 😢 

Ref [issue](https://github.com/doczjs/docz/issues/1488)

They were about to get that back with [this](https://github.com/doczjs/docz/pull/1159) PR but god knows what happened. It became stale and then went off (Have commented if they are getting back with this 🤞 )

Meanwhile, I was trying to get this functionality with repo's Docz config and it seems to be working fine. 

![image](https://user-images.githubusercontent.com/15359575/135727552-6391cf8e-5212-4dbe-a06d-a8a8b9fb991c.png)

![image](https://user-images.githubusercontent.com/15359575/135727579-cdd6bd06-dc41-49da-b71d-fad865311b91.png)
 
I basically tried to change the CSS of the `editor > pre` (this is not directly exposed so had to go by selector route 😕 ) to define a fixed height by default and toggle on the button state. If this sounds like a good way to start, maybe I can work further on this with some proper styling and label text that complies with our themes.

Let me know whenever possible. Thanks!

**Comment by Bhavin789** [comment]
A great suggestion on the usage of `Disclosure` by @joelwarrington-jobber  but just need to check if we can use our custom components in `Playground` or not.

**Comment by hosseintalebi** [comment]
Any update on this? Asking for a friend!

**Comment by chris-at-jobber** [comment]
Closing as Storybook's code examples seem to resolve this issue well enough. (Expand/collapse code examples, collapsed by default)
