### ISSUE TITLE
Make it easier to cycle through props

### ISSUE THREAD

**Issue by chris-at-jobber** [GetJobber/atlantis#680]
Most of our components have fairly limited props, where it's not that hard to edit data in the Playground and see the results.

For components like [Icon](https://atlantis.getjobber.com/components/icon), however, there are so many possible values for `name` that must be matched exactly for the prop to work, that the end user of the docs has to scroll through the entire page to search for the right icon.

In addition, cycling through color options is tedious.

And finally, for less-technical users like designers and PMs, it may be daunting to work in the Playground's editor.

Is there a solution to make it easier for consumers of our docs to explore the the visual effects of typed properties on a component?

**Comment by joelwarrington-jobber** [comment]
@chris-at-jobber thoughts on something similar to the Material UI icon search? I feel like if we made a component to show these variations and click through icons and copy their name or the component you've created would be helpful

https://mui.com/components/material-icons/

**Comment by chris-at-jobber** [comment]
I think that probably solves the problem for `Icon`, but I'm thinking that there might be something more useful across components, similar to Polaris (example from [Badge](https://polaris.shopify.com/components/images-and-icons/badge#navigation)):
![image](https://user-images.githubusercontent.com/39704901/134747516-5216f164-7d50-4fa4-8ff7-61ab3feb360f.png)

Although a `Select` for all of our Icon `name` and `color` variants would get out of control pretty fast, so maybe they are different problems, or at least there's an upper bound on how well a common solution would work 🤔

**Comment by JeffMarvin** [comment]
I'm thinking of taking a crack at this one... Are you assigning to devs for Hacktoberfest just to avoid overlaps? I'll probably have a few questions in the next day or so. :)

**Comment by joelwarrington-jobber** [comment]
@JeffMarvin yeah, best to avoid two people working on the same thing

**Comment by JeffMarvin** [comment]
Some first questions... 
I think a practical solution probably involves some kind of UI improvement for each prop that we list for a component, such that interacting with the UI for a prop can affect an example and/or the code sandbox. So, I'm starting with that assumption in mind.

1. We sometimes have more than one sandbox, or within that sandbox we may have more than one instance of the component being documented. I'm wondering about how we modify the sandbox components in that case... E.g. if someone selects a prop value, do we just modify the first instance of a component in the first sandbox? Do we modify all of them? (That might sound nice but could have destructive consequences if they've carefully set up some components to have values they want, and we overwrite them.) This is a practical but not urgent consideration, I'll probably start by modifying the first component in the first sandbox. But we should think about it... 
2. Practically, most props will work as drop downs or inputs. In extreme cases, like Icon, we probably want a more sophisticated way to search/select. I'll consider Icon as a special case and we may want to peel that off into a separate issue and/or PR. Again, not urgent as I think a dropdown works for most cases and I'll start there... but we probably want to start thinking about that. Beyond Icon, can you think of any other components/props that wouldn't fit into the drop down model?

**Comment by joelwarrington-jobber** [comment]
@JeffMarvin going to defer thoughts on that to @eddysims as he would have more context

**Comment by chris-at-jobber** [comment]
Closing as Storybook's controls do this
