### ISSUE TITLE
Add vertical option to the Divider component

### ISSUE THREAD

**Issue by joelwarrington-jobber** [GetJobber/atlantis#692]
The divider component can only be used to divide content in a traditional page flow (top down), but has no option to divide content which is in a left to right page flow.

**Comment by joelwarrington-jobber** [comment]
@chris-at-jobber, do you see any issue with this?

**Comment by chris-at-jobber** [comment]
Not off the top of my head - we do use this in a few places across the product and it would be nice to get off of using border utilities.
