### ISSUE TITLE
README: fix broken link to contribution guidelines

### ISSUE THREAD

**Issue by linhub15** [GetJobber/atlantis#693]
**Note**: this only happens when clicking from github. https://atlantis.getjobber.com/ works fine.
Clicking README hyperlink to contribution guidelines results in 404 not found. 

Expected URL: https://github.com/GetJobber/atlantis/blob/master/docs/CONTRIBUTING.md
Actual URL (404): https://github.com/GetJobber/atlantis/blob/master/CONTRIBUTING.md

### Fix 
~~add `docs/` to the link on line 164~~
~~from: `[contribution guidelines](/CONTRIBUTING.md) to learn how.`~~
~~to: `[contribution guidelines](/docs/CONTRIBUTING.md) to learn how.`~~
edit - on second thought, doing this might break the site link.

GitHub supports [relative links in README files](
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes#relative-links-and-image-paths-in-readme-files).
As long as Gatsby markdown parser is able to remove the `.` this would still work on the docs site and GitHub.

add `./` to the link on line 164 
from: `/CONTRIBUTING.md`
to: `./CONTRIBUTING.md`

**Comment by eddysims** [comment]
@linhub15 do you want to try this for `hacktoberfest`?

**Comment by linhub15** [comment]
Sure, I'll work on a PR for this.
