### ISSUE TITLE
Menu: First item should receive focus when opened

### ISSUE THREAD

**Issue by eddysims** [GetJobber/atlantis#697]
The first menu item does not receive focus when opened (user must tab to the first menu item).

**Comment by Bhavin789** [comment]
Hi @eddysims , I was looking at this issue, do we want to highlight `useCollectionQuery` when we click on `Hooks`?
Is this what we mean by first item being focussed?

<img width="317" alt="image" src="https://user-images.githubusercontent.com/15359575/135657362-bc3ef17c-d9f9-472b-ad45-1ac0de6e72ea.png">

**Comment by eddysims** [comment]
hey @Bhavin789 This is in regards to the [Menu](https://atlantis.getjobber.com/components/menu) component. When we open a Menu with the keyboard, we want the first menu item to be focused

**Comment by Bhavin789** [comment]
Oh ok, is there any sample usage to check the behavior? Can you help me with a keyboard command on how it behaves currently and where can I check that? Thanks!

**Comment by Bhavin789** [comment]
Absolutely clear now @joelwarrington-jobber @eddysims. Thanks for the video!

Yes, you can assign it to me. Will do my best to understand the code and check if this can be done. 

This is my first diving too deep into a11y 😅. Would be a great experience 😄!

**Comment by Bhavin789** [comment]
@joelwarrington-jobber @eddysims 
Have added a a PR for a quick enhancement: https://github.com/GetJobber/atlantis/pull/706

Raising PR here for the first time. Please let me know if I missed something in the process. Thanks!

**Comment by chris-at-jobber** [comment]
Thanks for your contribution @Bhavin789 !

**Comment by Bhavin789** [comment]
Glad could contribute @chris-at-jobber 😄. Learnt a lot about a11y and Docz for the first time 😃
