### ISSUE TITLE
React Markdown needs to be updated to latest version as its falling behind significantly 

### ISSUE THREAD

**Issue by joelzwarrington** [GetJobber/atlantis#792]
There are a bunch of things which need to be updated due to breaking changes.

Initially started in https://github.com/GetJobber/atlantis/pull/765 but don't have the capacity to continue the update. Hoping someone else can pick this up!

**Comment by chris-at-jobber** [comment]
Resolved in https://github.com/GetJobber/atlantis/pull/908/files
