### ISSUE TITLE
Documentation: placeholder link instead of Slack channel

### ISSUE THREAD

**Issue by patrickfoley** [GetJobber/atlantis#829]
On this page - https://developer.getjobber.com/docs - there's a reference to "Jobber's public Slack channel," but the link goes to example.com. That should probably be fixed or removed.

**Comment by chris-at-jobber** [comment]
Thanks @patrickfoley - the Developer Center is managed in a separate project but we're taking a look 👍

**Comment by joelzwarrington** [comment]
Hello @patrickfoley, thanks for bringing this to our attention, and apologies for the delay in response here!

We're in the process of setting up our community programs and don't have a public slack channel ready just yet. However if you're looking for support relating to developer center, please reach out to api-support@getjobber.com
