### ISSUE TITLE
high severity vulnerability

### ISSUE THREAD

**Issue by si4star** [GetJobber/atlantis#894]
Latest @jobber/components (v2.83.0) introduces a high severity vulnerability to our application:

![170662385-2a47474e-59df-4e71-ac7c-6f4f7d6abbd9](https://user-images.githubusercontent.com/84602681/170684820-843e4312-6a2b-45a5-a518-993f6edc4cb6.png)

**Comment by darryltec** [comment]
@si4star thanks for raising this issue! We have a fix for it coming soon https://github.com/GetJobber/atlantis/pull/896
